version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/jar/

hooks:
  ApplicationStop:
   - location: ./applicationStop.sh
          timeout: 30
          runas: ubuntu
  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 30
      runas: ubuntu