---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:11.0.5-jdk-stretch
      - image: circleci/mariadb:10.3.21-bionic-ram
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: csye6225
    steps:
      - checkout # check out source code to working directory
      #- restore_cache:
      #    key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      #- restore_cache:
      #    key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: sudo apt-get install default-mysql-client
      #- run:
      #    name: create database
      #    command: mysql -h 127.0.0.1 -u root -ppassword --execute="Create database csye6225"
      - run:
          name: assemble
          command: ./gradlew assemble
      - run:
          name: Run
          command: ./gradlew bootRun
      - run:
          name: Test
          command: ./gradlew test
      #- save_cache:
      #  paths:
      #    - ~/.gradle/wrapper
      #  key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      #- save_cache:
      #  paths:
      #     - ~/.gradle/caches
      #  key: v1-gradle-cache-{{ checksum "build.gradle" }}

workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check